name: Process Auto Changes
on:
  workflow_run:
    workflows: ["CI"]
    types:
      - completed
    branches: [main]
    
permissions:
  contents: write
jobs:
  process-changes:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup git
        run: |
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          
      - name: Install Hatch
        run: pip install hatch
        
      # Run code quality tools
      - name: Run code quality fixes
        run: |
          hatch run code-quality:format-fix
          hatch run code-quality:lint-fix
          if [ -n "$(git status --porcelain)" ]; then
            git add .
            git commit -m "style: auto-format and lint code with black and ruff"
            echo "Code quality changes committed"
          else
            echo "No code quality changes detected"
          fi
          
      # Run pipeline serialization
      - name: Generate pipeline serialization
        run: |
          hatch run dp:serialize-pipelines
          if [ -n "$(git status --porcelain dist/pipelines/)" ]; then
            git add dist/pipelines/
            git commit -m "chore: auto-serialize pipelines"
            echo "Pipeline serialization changes committed"
          else
            echo "No pipeline serialization changes detected"
          fi
          
      # Push any changes
      - name: Push changes
        run: |
          if [ -n "$(git log --oneline @{u}..HEAD)" ]; then
            echo "Pushing changes"
            git push
          else
            echo "No changes to push"
          fi
