name: Build and Push Pipelines

on:
  push:
    tags:
      - 'pipeline-*.*.*'  # Only runs on tags matching this pattern

env:
  DP_API_URL: https://api.cloud.deepset.ai


jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        pip install hatch

    - name: Build and push
      env:
        DP_API_KEY: ${{ secrets.DP_API_KEY }}
      run: hatch run dp:push-pipelines